---
##################################################################
# Example :  Storage Pool Playbook
####################################################################
- name: Storage Pool
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_global_variables.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
###################################################################
###  Create Storage Pools with Pool Volumes
###################################################################
    - name: Create Storage Pools with Pool Volumes
      block:
        - name: Create 1st Storage Pool "{{ storagepool_name_1 }}" with Pool Volumes
          hitachivantara.vspone_block.vsp.hv_storagepool:
            connection_info: "{{ connection_info }}"
            storage_system_info:
              serial: "{{ storage_serial }}"
            state: "{{ state_present }}"
            spec:
              name: "{{ storagepool_name_1 }}"
              type: "HDP"
              should_enable_deduplication: false
              depletion_threshold_rate: 80
              warning_threshold_rate: 70
              pool_volumes: "{{ [{'capacity': storagepool_size, 'parity_group_id': next_parity_group_id}] * 4 }}" 
          register: storage_pool_result_1

        - name: Create 2nd Storage Pool "{{ storagepool_name_2 }}" with Pool Volumes
          hitachivantara.vspone_block.vsp.hv_storagepool:
            connection_info: "{{ connection_info }}"
            storage_system_info:
              serial: "{{ storage_serial }}"
            state: "{{ state_present }}"
            spec:
              name: "{{ storagepool_name_2 }}"
              type: "HDP"
              should_enable_deduplication: false
              depletion_threshold_rate: 80
              warning_threshold_rate: 70
              pool_volumes: "{{ [{'capacity': storagepool_size, 'parity_group_id': next_parity_group_id_2}] * 4 }}"
          register: storage_pool_result_2


    - name: Set pool_id value
      ansible.builtin.set_fact:
        dp_pool_id_1: "{{ storage_pool_result_1.data.pool_id }}"
        dp_pool_id_2: "{{ storage_pool_result_2.data.pool_id }}"


#############################################################
# Get LDEVs ID from created pools
#############################################################
    - name: Get Ldev details from each new pool
      hitachivantara.vspone_block.vsp.hv_ldev_facts:
        connection_info: "{{ connection_info }}"
        spec:
          pool_id: "{{ item }}"
      loop: 
        - "{{ dp_pool_id_1 }}"
        - "{{ dp_pool_id_2 }}"  
      register: pool_id_result

    - name: Set Pool 1 LDEV IDs
      ansible.builtin.set_fact:
        pool_1_ldev_ids: "{{ pool_id_result.results[0].ansible_facts.volumes | map(attribute='ldev_id') | list }}"

    - name: Set Pool 2 LDEV IDs
      ansible.builtin.set_fact:
        pool_2_ldev_ids: "{{ pool_id_result.results[1].ansible_facts.volumes | map(attribute='ldev_id') | list }}"

    - name: Display Storage Pool Volumes ID
      ansible.builtin.debug:
        msg:
          - "Pool {{ dp_pool_id_1 }} LDEV IDs: {{ pool_1_ldev_ids }}"
          - "Pool {{ dp_pool_id_2 }} LDEV IDs: {{ pool_2_ldev_ids }}"


###################################################################
### Task 7 : Assign Name to Pool Volumes
###################################################################
    - name: Assign names to Pool Volumes
      block:
        - name: Assign names to Pool Volumes of "{{ storagepool_name_1 }}"
          hitachivantara.vspone_block.vsp.hv_ldev:
            connection_info: "{{ connection_info }}"
            storage_system_info:
              serial: "{{ storage_serial }}"
            state: "{{ state_present }}"
            spec:
              ldev_id: "{{ item }}"
              name: "{{ pvol_name_1 }}_{{ item_index + 1 }}"
          register: ldev_result_1
          loop: "{{ pool_1_ldev_ids }}"
          loop_control:
            index_var: item_index

        - name: Assign names to Pool Volumes of "{{ storagepool_name_2 }}"
          hitachivantara.vspone_block.vsp.hv_ldev:
            connection_info: "{{ connection_info }}"
            storage_system_info:
              serial: "{{ storage_serial }}"
            state: "{{ state_present }}"
            spec:
              ldev_id: "{{ item }}"
              name: "{{ pvol_name_2 }}_{{ item_index + 1 }}"
          register: ldev_result_2
          loop: "{{ pool_2_ldev_ids }}"
          loop_control:
            index_var: item_index

