---
####################################################################
# Example : Parity Group Management Playbook
####################################################################
- name: Parity Group Management
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_create.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 4 : Create Parity Group
    ####################################################################
    - name: Get all disk drives
      hitachivantara.vspone_block.vsp.hv_disk_drive_facts:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
      register: result

        #- name: Debug the result variable
        #ansible.builtin.debug:
        #var: result.ansible_facts.disk_drives.data

    - name: declare free drive list
      ansible.builtin.set_fact:
        free_drives: []

    - name: select drives which are available for new parity group creation
      ansible.builtin.set_fact:
        free_drives: "{{ free_drives + [item.drive_location_id] }}"
      loop: "{{ result.ansible_facts.disk_drives.data }}"
      when: item.usage_type == "FREE" and item.drive_type_name == drive_type_1 and item.total_capacity == drive_capacity_1

    - name: total free drives
      ansible.builtin.debug:
        msg: "total free drives is {{ free_drives | length }}"
      
    - name: Terminate workflow if number of drives is less than "{{ free_disk_drives }}"
      fail:
        msg: "Number of free drives is less than require for parity group. Terminating workflow !!!!"
      when: free_drives | length < free_disk_drives

    - name: select free drives
      ansible.builtin.set_fact:
        free_disk_drives: "{{ free_drives[0:4] }}"

    - name: Create new Parity Group on ID "{{ next_parity_group_id }}" with raid type "{{ paritygroup_raid_type_1 }}"
      hitachivantara.vspone_block.vsp.hv_paritygroup:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          parity_group_id: "{{ next_parity_group_id }}"
          raid_type: "{{ paritygroup_raid_type_1 }}"
          is_encryption_enabled: "{{ paritygroup_is_encryption_enabled_1 }}"
          is_copy_back_mode_enabled: "{{ paritygroup_is_copy_back_mode_enabled_1 }}"
          is_accelerated_compression_enabled: "{{ paritygroup_is_accelerated_compression_enabled_1 }}"
          drive_location_ids: "{{ free_disk_drives }}"
      ignore_errors: false
      register: result
