---
##############################################################################
##  main.yml to create & configure VSP storage for SAP HANA TDI Scale-up Sever
##############################################################################
- name: Configure VSP One Storage for SAP HANA TDI Scale-up Server with Single Storage Pool
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check vsp_storage variable
      ansible.builtin.fail:
        msg: "Error: vsp_storage variable is not defined or has an invalid value. It must be any VSP One model like 'b24/b26/b28' and use with -e option like: -e vsp_storage=b24"
      when: vsp_storage is not defined or vsp_storage not in ['b24', 'b26', 'b28']

    - name: Set vsp_storage variable (if undefined)
      ansible.builtin.set_fact:
        vsp_storage: "{{ vsp_storage | default(omit) }}"

- name: Configure Storage Ports
  import_playbook: 1_storage_port_create.yml

- name: Create & configure hostgroups for SAP HANA TDI Servers and then add WWNs of connected servers
  import_playbook: 2_hostgroup_create.yml

- name: Set Parity Group ID
  import_playbook: 3_paritygroup_get_pg_id.yml

- name: Create Parity Group with required RAID Type
  import_playbook: 4_paritygroup_create.yml

- name: Create Single Storage Pool with Pool Volumes for Scale-up SAP HANA TDI
  import_playbook: 5_storagepool_create.yml

- name: Create Vitual Volumes in Storage Pool and map those LUNs to SAP HANA TDI Hostgroup
  import_playbook: 6_vvol_creation_in_pool.yml

