---
######################################################################################
# Example :  Storage Pool Playbook
######################################################################################
- name: Storage Pool Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_delete.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    ######################################################################################
    # Task Name : Delete a pool including pool volumes
    ######################################################################################
    - name: Delete a pool "{{ storage_pool_name }}" including its pool volumes
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        state: "absent"
        spec:
          name: "{{ storage_pool_name }}"
          should_delete_pool_volumes: true
      register: pool_delete_result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: pool_delete_result

    ####################################################################
    # Task Name : Delete Parity Group
    ####################################################################
    - name: Delete Parity Group "{{ parity_group_id }}"
      hitachivantara.vspone_block.vsp.hv_paritygroup:
        connection_info: "{{ connection_info }}"
        state: "absent"
        spec:
          parity_group_id: "{{ parity_group_id }}"
      register: pg_delete_result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: pg_delete_result

