---
####################################################################
# Example : Storage Pool Facts Playbook
####################################################################
- name: Storage Pool Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_modify.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task 2 : Get Resource Group by name
    ####################################################################
    - name: Get all storage pools
      hitachivantara.vspone_block.vsp.hv_storagepool_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Print all storage pools summary only
      ansible.builtin.debug:
        msg: "{{ storage_pool_summary }}"
      vars:
        storage_pool_summary: >-
          {{
            {
              "Pool ID": item.pool_id,
              "Pool Name": item.pool_name,
              "Type": item.pool_type,
              "Num of LDEVs": item.num_of_ldevs,
              "Status": item.pool_status,
              "Used Capacity Rate (%)": item.used_capacity_rate,
              "Total Capacity (GB)": (item.total_pool_capacity_mb | int // 1024),
              "Used Capacity (GB)": ((item.total_pool_capacity_mb * item.used_capacity_rate // 100) | int // 1024)
            }
          }}
      loop: "{{ result.ansible_facts.storage_pool }}"
      loop_control:
        label: "{{ item.pool_name }}"

