---
####################################################################
# Example :  Storagesystem Facts Playbook
####################################################################
- name: StorageSystem Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get storage system facts
    ####################################################################
    - name: Get storage system facts
      hitachivantara.vspone_block.vsp.hv_storagesystem_facts:
        connection_info: "{{ connection_info }}"
      register: result

        #    - name: Debug the result variable
        #ansible.builtin.debug:
        #var: result
    - name: Display Storage System Information
      ansible.builtin.debug:
        msg: 
          - "Model: {{ result.ansible_facts.storage_system.model }}, Serial: {{ result.ansible_facts.storage_system.serial_number }}, Microcode: {{ result.ansible_facts.storage_system.microcode_version }}, IP: {{ storage_address }}"
          - "*** NOTE: Please verify the Microcode version to be latest before proceeding! ***"


    - name: Fail and exit if Storage system Model is not supported
      ansible.builtin.fail:
        msg: "ERROR: Unsupported storage system model '{{ result.ansible_facts.storage_system.model }}'. Permitted models are: VSP E/F/G Series only. Playbook execution aborted."
      when: result.ansible_facts.storage_system.model is search('B24|B26|B28|B85')

