##################################################################
# Example :  Storage Pool Playbook
####################################################################
- name: Storage Pool
  hosts: localhost
  gather_facts: false
  collections:
    - hitachivantara.vspone_block.vsp

  vars_files:
    - ~/playbooks/ansible_vault_vars/ansible_vault_storage_var.yml
    - vsp_direct_variables_create.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
###################################################################
### Task 5 : Create Storage Pool with Pool Volumes
###################################################################
    - name: Create Storage Pool with 8 Pool Volumes
      hitachivantara.vspone_block.vsp.hv_storagepool:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          name: "{{ storagepool_name_1 }}"
          type: "HDP"
          should_enable_deduplication: false
          depletion_threshold_rate: 80
          warning_threshold_rate: 70
          pool_volumes: "{{ [{'capacity': storagepool_size, 'parity_group_id': next_parity_group_id}] * 8 }}" 
      register: storage_pool_result


        #- name: Debug the result variable
        #ansible.builtin.debug:
        #var: storage_pool_result


    - name: Set pool_id value
      ansible.builtin.set_fact:
        dp_pool_id_1: "{{ storage_pool_result.data.pool_id }}"

    - name: Created Storage pool ID
      ansible.builtin.debug:
        msg: "Created Storage Pool ID: {{ dp_pool_id_1 }}, Pool Name: {{ storage_pool_result.data.pool_name }} and Size: {{ storage_pool_result.data.total_pool_capacity_mb }}"


#############################################################
# Get LDEVs ID from created pools
#############################################################
    - name: Get PVOLs detail from new pool "{{ storage_pool_result.data.pool_name }}"
      hitachivantara.vspone_block.vsp.hv_ldev_facts:
        connection_info: "{{ connection_info }}"
        spec:
          pool_id: "{{ dp_pool_id_1 }}"
      register: pool_id_result

    - name: Set PVOLs ID
      ansible.builtin.set_fact:
        pool_pvol_ids: "{{ pool_id_result.ansible_facts.volumes | map(attribute='ldev_id') | list }}"


    - name: Display Storage Pool Volumes ID
      ansible.builtin.debug:
        msg:
          - "HDP_Pool: {{ dp_pool_id_1 }} , LDEV_IDs: {{ pool_pvol_ids }}"
          

###################################################################
### Task 6 : Assign Name to Pool Volumes
###################################################################

    - name: Assign name to Pool Volumes of Storage Pool "{{ storage_pool_result.data.pool_name }}"
      hitachivantara.vspone_block.vsp.hv_ldev:
        connection_info: "{{ connection_info }}"
        storage_system_info:
          serial: "{{ storage_serial }}"
        state: "{{ state_present }}"
        spec:
          ldev_id: "{{ item }}"
          name: "{{ pvol_name_1 }}_{{ item_index + 1 }}"
      register: ldev_result
      loop: "{{ pool_pvol_ids }}"
      loop_control:
        index_var: item_index

